import { Injectable } from '@nestjs/common';
import { DomainError } from '../../domain/shared/result.js';

@Injectable()
export class DataHarnessService {
  private readonly store = new Map<string, string>();

  reset(): void {
    this.store.clear();
  }

  all(): Record<string, string> {
    return Object.fromEntries(this.store);
  }

  storeValue(key: string, value: string): void {
    this.set(key, value);
  }

  resolveObject<T>(input: T, mode: 'action' | 'assertion' = 'action'): T {
    if (typeof input === 'string') return this.resolve(input, mode) as T;
    if (Array.isArray(input)) return input.map((v) => this.resolveObject(v, mode)) as T;
    if (input && typeof input === 'object') {
      return Object.fromEntries(Object.entries(input).map(([k, v]) => [k, this.resolveObject(v, mode)])) as T;
    }
    return input;
  }

  private resolve(input: string, mode: 'action' | 'assertion'): string {
    return input.replace(/\{\{([^}]+)\}\}/g, (_m, exp: string) => {
      const [type, key, ...rest] = exp.split(':');
      if (mode === 'assertion' && (type === 'uniqueName' || type === 'uniqueEmail')) {
        const generated = this.store.get(key);
        if (generated) return generated;
        throw new DomainError('DYNAMIC_DATA_GENERATOR_IN_ASSERTION', `Generator ${type} is not allowed in assertions before it is generated by an action. Use {{ref:${key}}} in assertions`);
      }
      if (type === 'ref') {
        const value = this.store.get(key);
        if (!value) throw new DomainError('DYNAMIC_DATA_KEY_NOT_FOUND', `Run data key not found: ${key}`);
        return value;
      }
      if (type === 'uniqueName') return this.set(key, `${rest.join(':')} ${this.suffix()}`);
      if (type === 'uniqueEmail') return this.set(key, `${key}.${this.suffix()}@qa.local`);
      throw new DomainError('DYNAMIC_DATA_EXPRESSION_INVALID', `Unknown data expression: ${exp}`);
    });
  }

  private set(key: string, value: string): string {
    this.store.set(key, value);
    return value;
  }

  private suffix(): string {
    return `${Date.now()}-${Math.random().toString(16).slice(2, 6)}`;
  }
}
